### ISSUE TITLE
Animation flickers with iOS 10.3 and higher.

### ISSUE THREAD

**Issue by davidattias** [robertmryan/SwiftCustomTransitions#2]
I am observing an animation flicker (like a quick backward forward bounce) at the end of the interactive modal transition only on iOS 10.3+.

When I test with 10.2, it works as expected but there's a glitch on 10.3+.

Can you confirm this issue ?

**Comment by robertmryan** [comment]
Yep, I've noticed this, too. It used to be with complicated transitions and it sounds like it's more common in 10.3. See the following link for two workarounds. It's admittedly Objective-C answer, but the concept basically applies here, too.

https://stackoverflow.com/questions/23047350/uipercentdriveninteractivetransition-yielding-extraneous-animation-when-done

**Comment by robertmryan** [comment]
See https://github.com/robertmryan/SwiftCustomTransitions/commit/65a6eb60728fff8b8820f26c6b22ecf01de362e6 and https://github.com/robertmryan/SwiftCustomTransitions/commit/29b8a9bf4f1d51b17efe0fa7b626c50280c1d6d6, both encompassed in [version 1.0.1](https://github.com/robertmryan/SwiftCustomTransitions/releases/tag/1.0.1) of this repo.
